ignored-vulnerabilities:
    - id: GO-2026-4601
      silence-until: 2026-08-15
      info: https://pkg.go.dev/vuln/GO-2026-4601
    - id: GO-2026-4602
      silence-until: 2026-08-15
      info: https://pkg.go.dev/vuln/GO-2026-4602
    - id: GO-2026-4870
      silence-until: 2026-08-15
      info: https://pkg.go.dev/vuln/GO-2026-4870
    - id: GO-2026-4918
      silence-until: 2026-08-15
      info: https://pkg.go.dev/vuln/GO-2026-4918
    - id: GO-2026-4946
      silence-until: 2026-08-15
      info: https://pkg.go.dev/vuln/GO-2026-4946
    - id: GO-2026-4947
      silence-until: 2026-08-15
      info: https://pkg.go.dev/vuln/GO-2026-4947
    - id: GO-2026-4971
      silence-until: 2026-08-15
      info: https://pkg.go.dev/vuln/GO-2026-4971
    - id: GO-2026-4977
      silence-until: 2026-08-15
      info: https://pkg.go.dev/vuln/GO-2026-4977
    - id: GO-2026-4986
      silence-until: 2026-08-15
      info: https://pkg.go.dev/vuln/GO-2026-4986
    - id: GO-2026-5026
      silence-until: 2026-08-15
      info: https://pkg.go.dev/vuln/GO-2026-5026
    - id: GO-2026-5037
      silence-until: 2026-08-15
      info: https://pkg.go.dev/vuln/GO-2026-5037
    - id: GO-2026-5038
      silence-until: 2026-08-15
      info: https://pkg.go.dev/vuln/GO-2026-5038
    - id: GO-2026-5039
      silence-until: 2026-08-15
      info: https://pkg.go.dev/vuln/GO-2026-5039
    - id: GO-2026-5856
      silence-until: 2026-08-15
      info: https://pkg.go.dev/vuln/GO-2026-5856
    # Infinite loop on invalid input in golang.org/x/text
    # Found in: golang.org/x/text/unicode/norm@v0.31.0
    # Fixed in: golang.org/x/text/unicode/norm@v0.39.0
    - id: GO-2026-5970
      silence-until: 2026-09-02
      info: https://pkg.go.dev/vuln/GO-2026-5970
